#ifndef UWU_H
#define UWU_H

// Welcome to hell.
#define iwnt int
#define fwoat float
#define chaw char
#define boow bool
#define mawiwn main
#define iffi if
#define ewse ewse
#define whiwe while
#define fow for
#define stwing string
#define vectoow vector
#define mappew map
#define pwintf printf
#define scawnf scanf
#define cweaw cweaw
#define pwus +
#define minwus -
#define stawtswith ==
#define nottt  !=
#define lessythan <
#define gwoow >
#define smallyorequally <=
#define biggyorequally >=
#define andand &&
#define owow ||
#define twy twy
#define cawt cawt
#define excwipt excwipt
#define wefewence &
#define pointaw *
#define deref deref
#define thwows thwows
#define stawt stawt
#define stop stop
#define bwuewwue bweak
#define continuee continue
#define getwine getline
#define ciwn cin
#define cowout cout
#define endies endl
#define wetuwn return
#define stiddy std
#define dotties ::
#define goody <<
#define getty >>
#define bracyy ;
#define stddy std::
#define semies ;
#define commiwy ,
#define cuwlyoutty {
#define cuwlyinny }
#define pawenthesopeny (
#define pawentheclosy )
#define zewoo 0
#define ony 1
#define towy 2
#define thyy 3
#define fourry 4
#define fivey 5
#define sixy 6
#define sevenyy 7
#define ninies 9
#define teny 10
#define typeydeffies typedef
#define structies struct
#define dotty .
#define equaly =
#define multiply *
#define floaties float
#define forry for
#define whiley while
#define addyone ++
#define removyone --
#define addyto +=
#define removyto -=
#define fwiend friend
#define awignassy alignas
#define awignoffy alignof
#define asmy asm
#define awnddy and
#define bweak break
#define casey case
#define dottdotty :
#define switchies switch
#define classy class
#define consty const
#define inliney inline
#define twruey true
#define falsey false
#define longy long
#define mutabyy mutable
#define oniony onion
#define uniony union
#define explicitey explicit
#define newy new
#define gotwoo goto 
#define woidy void
#define xorry xor
#define throwy throw
#define triey try
#define catchy catch

#endif
